# Use a lightweight Python base image
FROM python:3.10-slim

# Set environment variables for Python
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# Set the working directory
WORKDIR /app

# Install Python dependencies
COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

# Copy the Flask app, templates, and static files
COPY . /app

# Expose the port for Flask
EXPOSE 5000

# Command to run the Flask server
CMD ["python", "app.py"]
