name: CI/CD for Dockerized Flask App with Frontend and Backend

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  backend-dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Backend Docker Image
      run: docker build ./backend --file ./backend/DockerFile --tag backend-app:$(date +%s)

  frontend-dockerbuild:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Frontend Docker Image
      run: docker build ./frontend --file ./frontend/DockerFile --tag frontend-app:$(date +%s)

  backend-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install dependencies
      working-directory: ./backend
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run Backend Tests
      working-directory: ./backend
      run: pytest

  frontend-build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Frontend Dependencies
      working-directory: ./frontend
      run: |
        npm install

    - name: Run Frontend Tests
      working-directory: ./frontend
      run: npm test

  build-and-publish:
    needs: [backend-build-and-test, frontend-build-and-test]
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to DockerHub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build and Push Backend Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./backend
        file: ./backend/DockerFile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/flask-backend:latest

    - name: Build and Push Frontend Docker Image
      uses: docker/build-push-action@v4
      with:
        context: ./frontend
        file: ./frontend/DockerFile
        push: true
        tags: ${{ secrets.DOCKER_USERNAME }}/frontend-app:latest

    - name: Image Digests
      run: |
        echo "Backend Image Digest: ${{ steps.backend-dockerbuild.outputs.digest }}"
        echo "Frontend Image Digest: ${{ steps.frontend-dockerbuild.outputs.digest }}"
